// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnbmfnddbnuglclnothy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uYm1mbmRkYm51Z2xjbG5vdGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTI3NjEsImV4cCI6MjA3MDY2ODc2MX0.61iC3vRztcM_MYgvJiKEkil9jVOLcIEb1Mqe8Nzz5oU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});